#### 데이터 전처리

###### - 레이블 인코딩

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [11]:
# 객체 생성
le = LabelEncoder()

# 학습 데이터 탐색
le.fit(items)

# 인코딩 실행
labels = le.transform(items)
print(labels)

# 단축코딩
le2 = LabelEncoder()
labels = le2.fit_transform(items)
print(labels)

# 최단축코딩
labels = LabelEncoder().fit_transform(items)
print(labels)


[0 1 4 5 3 3 2 2]
[0 1 4 5 3 3 2 2]
[0 1 4 5 3 3 2 2]


In [13]:
# 디코딩
le.inverse_transform(labels)

array(['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U4')

###### - 원핫 인코딩(One-Hot encoding)

In [16]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
oh_labels = ohe.fit_transform(labels.reshape(-1,1))
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [18]:
from tensorflow.keras.utils import to_categorical
to_categorical(labels)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)

###### - 표준화

In [20]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import pandas as pd

iris = load_iris()
iris_std = StandardScaler().fit_transform(iris.data)


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         150.000000        150.000000         150.000000        150.000000
mean            5.843333          3.057333           3.758000          1.199333
std             0.828066          0.435866           1.765298          0.762238
min             4.300000          2.000000           1.000000          0.100000
25%             5.100000          2.800000           1.600000          0.300000
50%             5.800000          3.000000           4.350000          1.300000
75%             6.400000          3.300000           5.100000          1.800000
max             7.900000          4.400000           6.900000          2.500000

In [25]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         150.000000        150.000000         150.000000        150.000000
mean            5.843333          3.057333           3.758000          1.199333
std             0.828066          0.435866           1.765298          0.762238
min             4.300000          2.000000           1.000000          0.100000
25%             5.100000          2.800000           1.600000          0.300000
50%             5.800000          3.000000           4.350000          1.300000
75%             6.400000          3.300000           5.100000          1.800000
max             7.900000          4.400000           6.900000          2.500000

In [26]:
iris_std = StandardScaler().fit_transform(iris.data)
df_std = pd.DataFrame(iris_std, columns=iris.feature_names)
df_std.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count       1.500000e+02      1.500000e+02       1.500000e+02      1.500000e+02
mean       -1.468455e-15     -1.823726e-15      -1.610564e-15     -9.473903e-16
std         1.003350e+00      1.003350e+00       1.003350e+00      1.003350e+00
min        -1.870024e+00     -2.433947e+00      -1.567576e+00     -1.447076e+00
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00     -1.183812e+00
50%        -5.250608e-02     -1.319795e-01       3.364776e-01      1.325097e-01
75%         6.745011e-01      5.586108e-01       7.627583e-01      7.906707e-01
max         2.492019e+00      3.090775e+00       1.785832e+00      1.712096e+00

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
lrc = LogisticRegression(random_state=2022)


In [30]:
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, stratify=iris.target, random_state=2022
)

lrc.fit(X_train,y_train)

d:\edu\venv\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=2022)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(
    iris_std, iris.target, stratify=iris.target, random_state=2022
)

lrc.fit(X_train,y_train)

LogisticRegression(random_state=2022)

###### - 정규화

In [33]:
from sklearn.preprocessing import MinMaxScaler

iris_mm = MinMaxScaler().fit_transform(iris.data)

In [36]:
df3 = pd.DataFrame(iris_mm, columns=iris.feature_names)
df3.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         150.000000        150.000000         150.000000        150.000000
mean            0.428704          0.440556           0.467458          0.458056
std             0.230018          0.181611           0.299203          0.317599
min             0.000000          0.000000           0.000000          0.000000
25%             0.222222          0.333333           0.101695          0.083333
50%             0.416667          0.416667           0.567797          0.500000
75%             0.583333          0.541667           0.694915          0.708333
max             1.000000          1.000000           1.000000          1.000000

In [38]:
X_train, X_test, y_train, y_test = train_test_split(
    iris_mm, iris.target, stratify=iris.target, random_state=2022
)

lrc.fit(X_train,y_train)
lrc.score(X_test, y_test)

0.9210526315789473